### PR TITLE
Hedm import docs

### PR DESCRIPTION
**Pull request by bnmajor**
Adds a section for quick load and the simple image series dialog

### CODE REVIEW

**Comment by bnmajor** [comment]
@psavery This is the PR I wanted to add more omega information to. I will update after we chat tomorrow.

**Comment by psavery** [comment]
This is wonderful, Brianna! I just updated this with a few fixes! The only thing needed is that the `omega_range_per_frame.gif` file appears to be missing. If we get that updated, then this looks good to go!

**Review by psavery — APPROVED** [review]
LGTM

**Review by psavery — APPROVED** [review]
LGTM

**Pull request merged**
