### PR TITLE
Add masking docs

### PR DESCRIPTION
**Pull request by bnmajor**

### CODE REVIEW

**Comment by bnmajor** [comment]
@psavery This is largely ready for review, although I could use some more help expanding the last section about the `masks to panel buffer` option - like why or when they may want to use that

**Comment by psavery** [comment]
> @psavery This is largely ready for review, although I could use some more help expanding the last section about the `masks to panel buffer` option - like why or when they may want to use that

They look good Brianna! I may make some minor edits, and then we can merge it.

Let's ask Saransh about that option. Otherwise, we can just say "If you would like to apply the masks to the HEXRD panel buffers, click the `Masks to Panel Buffer` button."

**Comment by bnmajor** [comment]
> They look good Brianna! I may make some minor edits, and then we can merge it.
> 
> Let's ask Saransh about that option. Otherwise, we can just say "If you would like to apply the masks to the HEXRD panel buffers, click the `Masks to Panel Buffer` button."

Sounds good! I just pushed one more commit to fix some spelling errors :upside_down_face:

**Comment by psavery** [comment]
@bnmajor Are you planning to make any changes/additions based on our discussion of when we want to convert masks to panel buffers? Or are we good?

**Comment by bnmajor** [comment]
> @bnmajor Are you planning to make any changes/additions based on our discussion of when we want to convert masks to panel buffers? Or are we good?

All set and ready for review!

**Review by psavery — APPROVED** [review]
Looks good! I made minor edits and embedded the YouTube video.

**Pull request merged**
